const actionEnum = {
    USER_AUTHENTICATED: "USER_AUTHENTICATED",
    USER_INFO_CHANGED: "USER_INFO_CHANGED",
    FRIENDS_QUILL_DATA_CHANGED: "FRIENDS_QUILL_DATA_CHANGED",
    TREND_QUILL_DATA_CHANGED: "TREND_QUILL_DATA_CHANGED",
    ADD_QUILL_MODAL_STATUS_CHANGED: "ADD_QUILL_MODAL_STATUS_CHANGED",
    MESSAGE_DRAWER_STATUS_CHANGED: "MESSAGE_DRAWER_STATUS_CHANGED",
    MESSAGE_DATA_CHANGED: "MESSAGE_DATA_CHANGED",
    MESSAGE_DETAIL_DRAWER_STATUS_CHANGED: "MESSAGE_DETAIL_DRAWER_STATUS_CHANGED",
    SELECTED_MESSAGE_CHANGED: "SELECTED_MESSAGE_CHANGED",
    GENERAL_INFO_DATA_CHANGED: "GENERAL_INFO_DATA_CHANGED",
    BOOK_DATA_CHANGED: "BOOK_DATA_CHANGED",
    SONG_DATA_CHANGED: "SONG_DATA_CHANGED",
    MAIN_CONTENT_STATUS_CHANGED: "MAIN_CONTENT_STATUS_CHANGED",
    DETAILED_GENERAL_INFO_CHANGED: "DETAILED_GENERAL_INFO_CHANGED",
    THEME_CHANGED: "THEME_CHANGED",
};

export default actionEnum;
